language: python
python:
- '3.8'
install:
- pip install -r requirements-travis.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: D+qbI2wqlAk416ltyNy2q0NoyPg/OskMZD0gJepAS7Qg16ynGJz7TYijs2/JOInvJee0SfdrWT+IHIU17FEEltkSZ7/41xVbb6xAi+XtgGgvA2aRHTFVSExM87zT1daH5fmfHYuVIp6c91lk3b3SECswBM0QLebZac8pzUXjaC/6AUKkOsDes8FqiY7WbEtfmly4pnO0iFkT/ZuFixEit1SFDQaHky4k225l3yu0rh0mmQ+WcL4lnbXq1VJvNzmpJNdXNyhwjwkxdo8Kly13btS3It1QTsM3sZ7y+n1RSF1SVs3UuejaBK0muev+F88C8fFys5xoNaqd7zqoQbp8gvjnlCxcaH4gFSaNXk3wR2SZilZ8sTZMwI0CmyfTzDj2AMzLB4/27WBEe+IOVY28SwQoShBWN8cGkQhk9eQPTrRT2Uc3JpLdKJR0OuXUvBJb5Cvh6r558Ztfmv5rgQWXvcWtfCOdeTGY6dOdYUTqJ4pt2xP2GhP4CVMkPzhQBtLSsKoQlHYk4NLelPbmaKq/A5MZsh+Yd2B5wN/jsIdrR56sMqJUNIKQurODs5kW95rOyZh9re09a3BostKIDNMktqBw9hZqvm6im24a5ockgNyssFWJFR6y2LtYIo6yzTqAh59wfW8NfhjYZD1C8ZkFJr54C48OKKXZr6vQW9Ab1NY=
  app: project-101-textbook-swap
  on:
    repo: uva-cs3240-s20/project-101-textbook-swap