language: python
python:
- '3.8'
install:
- pip install -r requirements-travis.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: u1ViteLNlbLw0OSAXuxcisG49QcJw18Z/cMInhixLt9DYrrEGiT+GfIaqrBrZOee88Qg8DgyljcNd+OJzXXsy75fDf1oaXifNY4a7SdqjolUBXthgF8t0JVmb5FbFAl3L1KrsiuEZ4a/FDLh8FJglvN45H4crm3AZMVfwabVwAEXuEbfBaSWpHk9X0L1e7co54h7mxO1njEEMjkiCFlECMiiFw8iB9vUsVdFiHUnmfqUUjb62nG3uUc/oquEogv3ItVIM/9chYQCr0DAtwS1CnPBOCdONjCqEVVVAKEr1+XW50/1jnV6G08izazAIqFJ0l1N/cMIN5W+g+xH7fJLe0aqL0kobJCuEgDPz0Ffnp1n61HmyCzyVeOl/+jxsrVJ3ftoxhul8nDtGKmvw5ugrmTVtxYbE4ahII4sF5v1Tc+05JLhXo/x7XcDp5TVP9vh/wpRc5Gm2CL9YWP3oxy+LAXwyCJ7yJmcK81NC7ZniKYHxrjVF+Itk3GKVWFVMqfvLyCr3VmIKp4DRX2KJdDIsAe7Ivqi5SQvcCKfcZVEAz4suXxrbBF15pBl8oYg5Wt3btqgHNKPQMIbML1k32WOeVOOQQ7MrRGgtiiiF20ITjJNJtPt2IJZjd+kiJ1x4aBOGl/nbYiKRPebpiLd5gwFRKsnQWzHmjHDXQA/3JXNPhA=
  app: project-101-textbook-swap
  on:
    repo: uva-cs3240-s20/project-101-textbook-swap
