language: python
python:
- '3.8'
install:
- pip install -r requirements-travis.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: vFH938+EDq5wa5tFEFTcAG1NIh6up66vUvAHPOaIIa8LnOSxCI+i3QywY0fk8pAehEr4govuZSRE+Wcequss7vePyEbde9JfRhQ31QLVd0jvNOQPX0Byup3P5kMGz5t5sOmcXdPD8eSrzUw+87bH4a7P46nCwkRX0s3GYjdwLrJ8BAxVu7GxDlmMs8XooNK+41Imofrj6pebuBgiWkLfE2ouo/gs/AmjIg1qTiwrrIUf1ls9CzEiOQHT3q+pH5NF32QpAd6RFveKL2ojBecPqZVvWmDuQNNI3zGC7tae99C+Fr9sKmV8xEhntzWq441mQq9Z/SvZvChAP6PsD8j35hjTh984jCd/5SAZtbZbDcchUNRDyOTxlldYxz5B/wwYzZbK3yPpEh4lZVvztr6LTS/eclOrcDDYzZwkscVrIBnE1ui8Qw4U7J7PA6IMJcrAfa3Lj8HNQtijv4ujnC6gcgAQ8exFcW4Z6CETJL84NjWA3V6uJLWCGaqijUKPu4s3KDbrRMq/wrWaFBE85V9TFH+bAdU3foJmBLmLKCpiwur3UwGBsfoMiLmsAaXEYvEuHnhYJOJoNLk+QSQuuznWAAaWFBL0kRR0RmGLvbl4npTOqP9CF91E2e8R7aTv1yXWgDTkPPmuiCZZ0zxMQPQWh+LK9DcgtZVPyRGQnAwOiDw=
  app: textbookswapuva
  on:
    repo: uva-cs3240-s20/project-101-textbook-swap
