language: python
python:
- '3.8'
install:
- pip install -r requirements-travis.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: 2v0QmsIMzG+K4bOIWDyYVZpCx4Y3ur3L8a4/RwIEVCqItb40Yui0lZQC6TSRVijl396LDxcFqtaYlkL5HLKrUtQgiQLJQ2DJCKf78p2XmOcU0RCR5/aMKDcW9kPdR+dEUWNVSfzzlDZxPYzLv+8ib8r5txeS4M0h9ZZFQ4zY5QlGbKN8/OTAeeMlnTuw1w2cXtWX0NrhKrJeH4nQw5qWp7TPzswyBThouw/kaMM3EIPIZQD+0SclcDLSeUXESVEiQ/40wF6UQmqns93UguWyDyHTCq8lUva10BuxllMh7kn9AG8kUjs91NbJR0WsFydO2Aj52lACh8twzT57qiStqjjSkgpXFvXY4Aj+DQJiWHqR2H+A3nx3r+pgLN4L6pm0Y0rlc4/GF6cRwE1udKZzdej3Rjlj7UbfKeebvbSoTtTfLh8FXWD1OgKddsDffwD9ja+dUWeY+JsJJfhvpfyCGvaFCLjIbKDdbw5cjLI73c92kAvdRJkrxEe+TUYJmKQVA/1vNVzaM0ZOESeqXHLCTTyyuosBKcp4E58iVpLjf1c2mTxbzhllDWzPcQvWThEmikKio8G4Z3pq+9WDJvyAeSWV6ShOdlDAPmevWT8o2dfCs6HfZ8D2tAqaPtwjalGA00XIPTL1XM1sYZcMCkh7IY2wXrlxW1mW+wljJZsVDfc=
  app: project-101-textbook-swap
  on:
    repo: uva-cs3240-s20/project-101-textbook-swap
