# Generated by Django 3.0.3 on 2020-04-13 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('imagefile', models.ImageField(null=True, upload_to='images/')),
                ('phonenumber', models.CharField(max_length=12, null=True)),
                ('major', models.CharField(max_length=50, null=True)),
                ('year', models.CharField(max_length=4, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewee_name', models.CharField(max_length=100, null=True)),
                ('reviewee_username', models.CharField(max_length=100, null=True)),
                ('review_book', models.CharField(max_length=100, null=True)),
                ('review_description', models.TextField(max_length=1000, null=True)),
                ('review_score', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='5', max_length=20)),
                ('reviewer_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.Profile')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.Conversation')),
                ('in_response_to', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.Message')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, null=True)),
                ('item_isbn', models.CharField(max_length=100, null=True)),
                ('item_edition', models.IntegerField(null=True)),
                ('item_author', models.CharField(max_length=100, null=True)),
                ('item_course', models.CharField(max_length=100, null=True)),
                ('item_price', models.IntegerField(null=True)),
                ('item_image', models.ImageField(null=True, upload_to='images/')),
                ('item_condition', models.CharField(choices=[('Like New', 'Like New'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], default='Brand New', max_length=20)),
                ('item_posted_date', models.DateField(null=True)),
                ('item_description', models.TextField(max_length=1000, null=True)),
                ('item_seller_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.Profile'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.Item'),
        ),
    ]
