# Generated by Django 3.0.3 on 2020-04-04 04:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.Profile')),
                ('in_response_to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='marketplace.Message')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.Profile')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.Item')),
                ('root_message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='marketplace.Message')),
            ],
        ),
    ]
