# Generated by Django 3.0.3 on 2020-03-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phonenumber',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
