# Generated by Django 3.0.3 on 2020-03-30 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_title',
            field=models.CharField(default='author_placeholder', max_length=100),
            preserve_default=False,
        ),
    ]
