# Generated by Django 3.0.2 on 2020-02-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='major',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phonenumber',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='year',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
