# Generated by Django 3.0.3 on 2020-04-04 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_conversation_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='in_response_to',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.Message'),
        ),
    ]
