# Generated by Django 3.0.3 on 2020-03-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_profile_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='major',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='year',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
