# Generated by Django 3.0.3 on 2020-03-30 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_item_item_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_title',
            new_name='item_author',
        ),
    ]
