# Generated by Django 3.0.3 on 2020-03-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_auto_20200302_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='imagefile',
            field=models.ImageField(default='empty-profile.png', upload_to='images/'),
        ),
    ]
