# Generated by Django 3.0.3 on 2020-03-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_auto_20200330_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_course',
            field=models.CharField(default='CS 1100', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='item_edition',
            field=models.IntegerField(default='5'),
            preserve_default=False,
        ),
    ]
