# Generated by Django 3.0.3 on 2020-03-02 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_profile_imagefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_ratings',
        ),
    ]
