# Generated by Django 3.0.3 on 2020-04-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_price',
            field=models.IntegerField(null=True),
        ),
    ]
