# Generated by Django 3.0.3 on 2020-03-02 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_auto_20200225_1310'),
        ('marketplace', '0005_remove_profile_user_ratings'),
    ]

    operations = [
    ]
