# Generated by Django 3.0.3 on 2020-04-04 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_auto_20200403_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_posted_date',
            field=models.DateField(null=True),
        ),
    ]
