# Generated by Django 3.0.3 on 2020-04-04 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_auto_20200403_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_course',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_edition',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
