# Generated by Django 3.0.3 on 2020-04-10 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_item_item_isbn'),
        ('marketplace', '0004_auto_20200405_2117'),
    ]

    operations = [
    ]
