# Generated by Django 3.0.3 on 2020-04-14 16:23

from django.db import migrations, models
import django.db.models.deletion
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_merge_20200410_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(default='No name', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='item_seller_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='marketplace.Profile'),
            preserve_default=False,
        ),
        TrigramExtension(),
    ]
