# Generated by Django 3.0.3 on 2020-04-12 01:52

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_merge_20200410_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phonenumber',
            field=phone_field.models.PhoneField(max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
