# Generated by Django 3.0.3 on 2020-04-12 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_merge_20200410_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='in_response_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.Message'),
        ),
    ]
