# Generated by Django 3.0.3 on 2020-04-12 02:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_auto_20200411_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
