# Generated by Django 3.0.3 on 2020-04-14 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0016_auto_20200412_1136'),
        ('marketplace', '0012_trigram_20200414_1123'),
    ]

    operations = [
    ]
