# Generated by Django 3.0.3 on 2020-04-26 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0018_auto_20200415_1326'),
        ('marketplace', '0018_auto_20200425_1712'),
    ]

    operations = [
    ]
