# Generated by Django 3.0.3 on 2020-04-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0020_auto_20200425_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_author',
            field=models.CharField(max_length=101, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_course',
            field=models.CharField(max_length=102, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_description',
            field=models.TextField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
