# Generated by Django 3.0.3 on 2020-04-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0021_auto_20200426_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_course',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
