# Generated by Django 3.0.3 on 2020-04-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0022_auto_20200426_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_description',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_edition',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
